# Generated by Django 5.1.3 on 2024-11-18 10:22

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
        ('wagtailcore', '0094_alter_page_locale'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='BlogPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('date', models.DateField(verbose_name='Post date')),
                ('name', models.CharField(default='', help_text='Blog Name', max_length=225, verbose_name='Blog Name')),
                ('content', wagtail.fields.StreamField([('content_block', 4)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'max_length': 250, 'required': True}), 1: ('wagtail.blocks.RichTextBlock', (), {'editor': 'with_table', 'required': True}), 2: ('wagtail.blocks.StructBlock', [[('heading', 0), ('content', 1)]], {}), 3: ('wagtail.blocks.ListBlock', (2,), {'required': True}), 4: ('wagtail.blocks.StructBlock', [[('content', 3)]], {})}, null=True)),
                ('blog_image', models.ForeignKey(blank=True, help_text='Blog image', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.blogcategory', verbose_name='Blog Category')),
            ],
            options={
                'verbose_name': 'Blog Page',
                'verbose_name_plural': 'Blog Pages',
            },
            bases=('wagtailcore.page',),
        ),
    ]
