# Generated by Django 5.1.3 on 2024-11-18 10:52

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blogcategory_blogpage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpage',
            name='content',
            field=wagtail.fields.StreamField([('content_block', 4)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'max_length': 250, 'required': True}), 1: ('wagtail.blocks.RichTextBlock', (), {'editor': 'default', 'required': True}), 2: ('wagtail.blocks.StructBlock', [[('heading', 0), ('content', 1)]], {}), 3: ('wagtail.blocks.ListBlock', (2,), {'required': True}), 4: ('wagtail.blocks.StructBlock', [[('content', 3)]], {})}, null=True),
        ),
        migrations.AlterField(
            model_name='blogpage',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name='Post date'),
        ),
    ]
