# Generated by Django 5.1.3 on 2024-11-11 08:24

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0094_alter_page_locale'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectsIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro', wagtail.fields.RichTextField(blank=True)),
                ('body', wagtail.fields.RichTextField(blank=True)),
            ],
            options={
                'verbose_name': 'Project Index Page',
                'verbose_name_plural': 'Project Index Pages',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('introduction', wagtail.fields.RichTextField(help_text='Add Introduction', verbose_name='Introduction')),
                ('description', wagtail.fields.RichTextField(blank=True, default='', help_text='Add description', null=True, verbose_name='Description')),
                ('id_number', models.IntegerField(help_text='Add ID Number')),
                ('whatsapp_number', models.IntegerField(help_text='Add Whatsapp Number')),
                ('call_number', models.IntegerField(help_text='Add Number')),
                ('image', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtailimages.image')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectsPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('project_name', models.CharField(default='', help_text='Project Name', max_length=225, verbose_name='Project Name')),
                ('project_description', wagtail.fields.RichTextField(blank=True, default='', help_text='Project description', null=True, verbose_name='Project description')),
                ('communities', models.CharField(blank=True, choices=[('Dubaic', 'Dubaic'), ('Abu Dhabic', 'Abu Dhabic')], max_length=20, null=True)),
                ('developers', models.CharField(blank=True, choices=[('DubaiDev', 'DubaiDev'), ('Abu Dhabidev', 'Abu Dhabidev')], max_length=20, null=True)),
                ('content', wagtail.fields.StreamField([('text_block', 7), ('about_block', 14), ('photo_gallery_block', 18), ('card_block_with_link', 19), ('text_card_block', 21), ('faq_block', 26), ('location_block', 37), ('amenities_block', 40), ('floor_plan_block', 42)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'help_text': 'Add your heading', 'required': True}), 1: ('wagtail.blocks.CharBlock', (), {'help_text': 'Add sub heading', 'required': True}), 2: ('wagtail.blocks.RichTextBlock', (), {'help_text': 'Add description', 'required': False}), 3: ('wagtail.blocks.CharBlock', (), {'help_text': 'Enter the label of the link', 'required': False}), 4: ('wagtail.blocks.URLBlock', (), {'help_text': 'Enter a URL', 'required': False}), 5: ('wagtail.blocks.StructBlock', [[('label', 3), ('link_url', 4)]], {}), 6: ('wagtail.blocks.ListBlock', (5,), {'help_text': 'Add button/link information to this section', 'label': 'Add link details', 'max_num': 2, 'min_num': 0}), 7: ('wagtail.blocks.StructBlock', [[('heading', 0), ('sub_heading', 1), ('description', 2), ('links', 6)]], {}), 8: ('wagtail.blocks.CharBlock', (), {'help_text': 'Add sub heading', 'required': False}), 9: ('wagtail.blocks.RichTextBlock', (), {'help_text': 'Add additional text', 'required': False}), 10: ('wagtail.blocks.CharBlock', (), {'help_text': 'Add your heading', 'required': False}), 11: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': False}), 12: ('wagtail.blocks.StructBlock', [[('heading', 10), ('sub_heading', 10), ('image', 11), ('description', 2)]], {}), 13: ('wagtail.blocks.ListBlock', (12,), {'help_text': 'Add card to this section', 'label': 'Add card details'}), 14: ('wagtail.blocks.StructBlock', [[('heading', 0), ('sub_heading', 8), ('description', 9), ('links', 6), ('cards', 13)]], {}), 15: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': True}), 16: ('wagtail.blocks.StructBlock', [[('image', 15)]], {}), 17: ('wagtail.blocks.ListBlock', (16,), {'label': 'Add Images'}), 18: ('wagtail.blocks.StructBlock', [[('heading', 0), ('image', 17)]], {}), 19: ('wagtail.blocks.StructBlock', [[('heading', 10), ('sub_heading', 10), ('image', 11), ('description', 2), ('links', 6)]], {}), 20: ('wagtail.blocks.ListBlock', (12,), {}), 21: ('wagtail.blocks.StructBlock', [[('heading', 10), ('sub_heading', 10), ('description', 2), ('card', 20)]], {}), 22: ('wagtail.blocks.CharBlock', (), {'help_text': 'Add your question', 'required': True}), 23: ('wagtail.blocks.RichTextBlock', (), {'help_text': 'Add your answer', 'required': False}), 24: ('wagtail.blocks.StructBlock', [[('question', 22), ('answer', 23)]], {}), 25: ('wagtail.blocks.ListBlock', (24,), {'help_text': 'Add frequently asked questions to this section', 'label': 'Add FAQ'}), 26: ('wagtail.blocks.StructBlock', [[('heading', 10), ('sub_heading', 8), ('description', 9), ('points', 25)]], {}), 27: ('wagtail.blocks.FloatBlock', (), {'help_text': 'Add Latitude of the location', 'required': False}), 28: ('wagtail.blocks.FloatBlock', (), {'help_text': 'Add Longitude of the location', 'required': False}), 29: ('wagtail.blocks.ChoiceBlock', [], {'blank': True, 'choices': [('Dubai', 'Dubai'), ('Abu Dhabi', 'Abu Dhabi'), ('Sharjah', 'Sharjah')], 'help_text': 'Nearby Locations', 'max_length': 20, 'null': True}), 30: ('wagtail.blocks.FloatBlock', (), {'help_text': 'Add Latitude of the nearby location', 'required': False}), 31: ('wagtail.blocks.FloatBlock', (), {'help_text': 'Add Longitude of the nearby location', 'required': False}), 32: ('wagtail.blocks.FloatBlock', (), {'help_text': 'Add distance in Kilometer', 'required': False}), 33: ('wagtail.blocks.StructBlock', [[('nearbylocation', 29), ('latitude', 30), ('longitude', 31), ('distance', 32)]], {}), 34: ('wagtail.blocks.ListBlock', (33,), {}), 35: ('wagtail.blocks.StructBlock', [[('heading', 1), ('description', 2), ('locations', 34)]], {}), 36: ('wagtail.blocks.ListBlock', (35,), {}), 37: ('wagtail.blocks.StructBlock', [[('heading', 10), ('latitude', 27), ('longitude', 28), ('nearby_locations', 36)]], {}), 38: ('wagtail.snippets.blocks.SnippetChooserBlock', (), {'target_model': 'project.Amenities'}), 39: ('wagtail.blocks.ListBlock', (38,), {}), 40: ('wagtail.blocks.StructBlock', [[('heading', 10), ('amenities', 39)]], {}), 41: ('wagtail.blocks.ListBlock', (16,), {}), 42: ('wagtail.blocks.StructBlock', [[('heading', 10), ('sub_heading', 10), ('description', 2), ('images', 41)]], {})}, null=True)),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='project.agent')),
                ('project_image', models.ForeignKey(blank=True, help_text='Project image', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'verbose_name': 'Project Page',
                'verbose_name_plural': 'Project Pages',
            },
            bases=('wagtailcore.page',),
        ),
    ]
