# Generated by Django 5.1.3 on 2024-11-11 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_amenities'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectspage',
            name='floor_plan',
            field=models.FileField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
