# Generated by Django 5.1.3 on 2024-11-21 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='careerindexpage',
            options={'verbose_name': 'Career Index Page', 'verbose_name_plural': 'Career Index Pages'},
        ),
    ]
