# Generated by Django 5.1.3 on 2024-11-21 10:46

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0002_alter_careerindexpage_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='careerpage',
            options={'verbose_name': 'Career Page', 'verbose_name_plural': 'Career Pages'},
        ),
        migrations.AlterField(
            model_name='careerpage',
            name='content',
            field=wagtail.fields.StreamField([('image_text_card_block', 3), ('faq_block', 11), ('blog_block', 14)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'help_text': 'Enter the card title', 'required': True}), 1: ('wagtail.blocks.TextBlock', (), {'help_text': 'Enter the description', 'required': False}), 2: ('wagtail.images.blocks.ImageChooserBlock', (), {'help_text': 'Select the background image for the card', 'required': True}), 3: ('wagtail.blocks.StructBlock', [[('title', 0), ('description', 1), ('image', 2)]], {'group': 'Blocks'}), 4: ('wagtail.blocks.CharBlock', (), {'help_text': 'Add your heading', 'required': False}), 5: ('wagtail.blocks.CharBlock', (), {'help_text': 'Add sub heading', 'required': False}), 6: ('wagtail.blocks.RichTextBlock', (), {'help_text': 'Add additional text', 'required': False}), 7: ('wagtail.blocks.CharBlock', (), {'help_text': 'Add your question', 'required': True}), 8: ('wagtail.blocks.RichTextBlock', (), {'help_text': 'Add your answer', 'required': False}), 9: ('wagtail.blocks.StructBlock', [[('question', 7), ('answer', 8)]], {}), 10: ('wagtail.blocks.ListBlock', (9,), {'help_text': 'Add frequently asked questions to this section', 'label': 'Add FAQ'}), 11: ('wagtail.blocks.StructBlock', [[('heading', 4), ('sub_heading', 5), ('description', 6), ('points', 10)]], {'group': 'Blocks'}), 12: ('wagtail.blocks.PageChooserBlock', (), {'help_text': 'Choose a blog page', 'required': True}), 13: ('wagtail.blocks.ListBlock', (12,), {'help_text': 'Add multiple blog pages to this block', 'label': 'Blog Pages'}), 14: ('wagtail.blocks.StructBlock', [[('blog_pages', 13)]], {'group': 'Blog Blocks'})}, null=True),
        ),
    ]
